module.exports={
    colors:{
     col1:'white',
     text1:'red',
     text2:'grey',
     text3:'black'
    },
    titles:{
        title1:30,
        btntxt:20,
    },
    btn1:{
        width:'80%',
        height:50,
        backgroundColor:'red',
        borderRadius:10,
        alignItems:'center',
        justifyContent:'center',
        elevation:10,
        color:'white',
        marginBottom:10
    },
    hr80:{
        width:'80%',
        borderBottomColor:'#E0E0E0',
        borderBottomWidth:1,
        marginVertical:15,
    },
    veg:{
        height:20,
        width:20,
        backgroundColor:'green',
        borderRadius:5
    },
    nonveg:{
        height:20,
        width:20,
        backgroundColor:'red',
        borderRadius:5
    },
    navbtn:{
        backgroundColor:'red',
        width:50,
        height:50,
        alignItems:'center',
        justifyContent:'center',
        elevation:10,
        borderRadius:50,
        //borderTopLeftRadius:0
    },
    navbtnin:{
        color:'white',
    },
    navbtnout:{
        position:'relative',
        top:0,
        left:0,
        zindex:10
    },
}